name: Test if Project builds

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: building
  cancel-in-progress: true

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Checkout build repo
        uses: actions/checkout@v6
        with:
          repository: RE-Pepper/RE-Pepper-Build
          token: ${{ secrets.GH_TOKEN }}
          path: setup

      - name: Setup
        run: |
          cp ./setup/ver/* ./data/ver -rf
          rm -rf ./setup/ver
          sudo apt-get update
          sudo apt-get install -y cmake make python3 python3-pip python-is-python3
          python -m pip install --no-cache-dir colorama capstone pyelftools requests argcomplete watchdog python-Levenshtein cxxfilt GitPython matplotlib numpy mplcursors

      - name: Build & Parse
        run: | 
          VERSIONS=(); for dir in ./data/ver/*/; do [[ -f "$dir/map.csv" ]] && VERSIONS+=("${dir%/}"); done; VERSIONS=("${VERSIONS[@]##*/}")
          did_run=false
          for v in "${VERSIONS[@]}"; do
              echo "Now $v"
              python make.py "$v"
              echo "Finished $v"
              did_run=true
          done

          if [ -z "$did_run" ]; then
              echo "No versions found."
              exit 1
          fi
